export const projects = [
  {
    id: 'relichunterszero',
    date: 'January 2025',
    title: 'Relic Hunters Zero',
    video: '/relic_hunters_zero/video.mov',
    VIDEO_ID: 'MAngPW7t4kw',
    youtubeUrl: 'https://www.youtube.com/embed/MAngPW7t4kw?si=uFvl5x-ZpuN7ASZz',
    images: [
      '/relic_hunters_zero/image.png',
      '/relic_hunters_zero/image.png',
      '/relic_hunters_zero/image.png',
      '/relic_hunters_zero/image.png',
    ],
    genre: 'Top-down shooter',
    description: [
      'Event-driven programming',
      'object pullling',
      'Dynamic Delayed UI',
      'Dynamic Scoring System',
      'Dynamic camera effects',
      'Diverse Firing Systems',
      '2D Ray casting',
      'destructible elements',
    ],
    buildUrl: '/relic_hunters_zero/index.html',
    skills: ['Unity', 'C#', '2D'],
  },
  {
    id: 'transformer',
    date: 'December 2018',
    title: 'Transformer',
    video: '/transformer/video.mov',
    youtubeUrl: 'https://youtu.be/IVuhzXUq6Fc',
    images: ['/transformer/image.png'],
    genre: 'action-adventure',
    description: [
      'Multi-threaded Run-time Loading',
      'Vehicle-Robot Mode Switching',
      'Optimized Stepwise Collision Detection',
      '3D Shadow Rendering',
      'Shader',
      'Lighting Effects',
      'Adaptive Sound by Space',
      'Graphics and Sound Settings',
    ],
    buildUrl: '/transformer/index.html',
    skills: ['DirectX', 'C++', '3D'],
  },
  {
    id: 'metalslug2',
    date: 'March 2016',
    title: 'Metal Slug 2',
    video: '/metal_slug_2/video.mov',
    VIDEO_ID: 'ilYA-aTWyRk',
    youtubeUrl: 'https://www.youtube.com/embed/ilYA-aTWyRk?si=HoWikGon3OCnwd0q',
    images: [
      '/metal_slug_2/0.png',
      '/metal_slug_2/1.png',
      '/metal_slug_2/2.png',
      '/metal_slug_2/4.png',
      '/metal_slug_2/5.png',
      '/metal_slug_2/6.png',
      '/metal_slug_2/7.png',
      '/metal_slug_2/8.png',
    ],
    genre: 'Run and gun',
    description: [
      'multiple State machine',
      'Smooth Motion Sync',
      'Parallax Background Effect',
      'Cinematic Event',
      'Interaction with items',
    ],
    skills: ['Win32', 'C++', '2D'],
  },
  {
    id: 'omok',
    date: 'April 2016',
    title: 'Omok',
    video: '/omok/video.mov',
    youtubeUrl: 'https://youtu.be/GIpu8ZysW7s',
    images: ['/omok/image.png'],
    genre: 'board game',
    description: ['Console pixel art'],
    buildUrl: '/omok/index.html',
    skills: ['Win32', 'C', '2D'],
  },
];
